# Generated by Django 5.2.6 on 2025-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('flower', 'Flower'), ('god', 'God'), ('goddess', 'Goddess')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
