# Generated by Django 5.2.6 on 2025-09-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('hobby', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
